 curl --request GET \
   --url https://api.myanimelist.net/v2/anime/season/2024/summer?fields=id,title,mean,num_list_users,media_type,status,num_episodes,start_season&limit=500&sort=num_list_users&nsfw=true \
   --header 'X-MAL-CLIENT-ID: 8bda3d8bbc449e438a88d199e19423d4'